import { Metadata } from "next";
import { cookies } from "next/headers";
import React, { Suspense } from "react";
import { RefineKbarProvider } from "@refinedev/kbar";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getLocale } from "next-intl/server";

import { AntdRegistry } from "@ant-design/nextjs-registry";
// import "@refinedev/antd/dist/reset.css";
import "./globals.css";
import { authProviderServer } from "@providers/auth-provider/auth-provider.server";
import { ColorModeContextProvider } from "@contexts/color-mode";
import { ServerAuthProvider } from "@contexts/server-auth";
import { IUser } from "@interfaces/user";
import { RefineProvider } from "@/components/RefineProvider";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const theme = cookieStore.get("theme");
  const defaultMode = theme?.value === "dark" ? "dark" : "light";

  const identity = (await authProviderServer.getIdentity()) as
    | IUser
    | undefined;

  // Get locale and messages for next-intl
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale}>
      <body>
        <Suspense>
          <AntdRegistry>
            <NextIntlClientProvider messages={messages} locale={locale}>
              <RefineKbarProvider>
                <ColorModeContextProvider defaultMode={defaultMode}>
                  <ServerAuthProvider initialUser={identity}>
                    <RefineProvider>{children}</RefineProvider>
                  </ServerAuthProvider>
                </ColorModeContextProvider>
              </RefineKbarProvider>
            </NextIntlClientProvider>
          </AntdRegistry>
        </Suspense>
      </body>
    </html>
  );
}
